import 'dotenv/config';
import { execFile } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdir, readdir, rename, rm } from 'node:fs/promises';
import path from 'node:path';
import * as readline from 'node:readline';
import { promisify } from 'node:util';
import { Command } from 'commander';
import { Client } from 'pg';
import { display } from './helpers/console-display';

const execFileAsync = promisify(execFile);

const basePath = '/var/www/html';
const migrationsPath = path.join(basePath, 'src/database/migrations');
const backupPath = path.join(basePath, '.migrations-backup');
const dataSourcePath = './src/config/data-source.config.ts';

type DatabaseConfig = {
	host: string;
	port: number;
	user: string;
	password: string;
	database: string;
};

/**
 * Consolidates every migration into a single one describing the current entity state.
 *
 * The generated file is only trustworthy because it is produced against an empty database
 * and then replayed against a second empty database: TypeORM's `migration:generate` emits a
 * *diff*, so pointing it at a populated database would silently produce a partial schema.
 */
class MigrationConsolidator {
	private readonly rl: readline.Interface;

	private backupDir = '';

	constructor(
		private readonly config: DatabaseConfig,
		private readonly options: {
			name: string;
			yes: boolean;
			baseline: boolean;
			keepBackup: boolean;
		},
	) {
		this.rl = readline.createInterface({
			input: process.stdin,
			output: process.stdout,
		});
	}

	private async askConfirmation(question: string): Promise<boolean> {
		return new Promise((resolve) => {
			this.rl.question(`${question} (Yes / No): `, (answer) => {
				resolve(['y', 'yes'].includes(answer.trim().toLowerCase()));
			});
		});
	}

	/**
	 * Connects to the `postgres` maintenance database: CREATE/DROP DATABASE cannot run
	 * inside a transaction, nor against the database being replaced.
	 */
	private async onMaintenance<T>(
		action: (client: Client) => Promise<T>,
	): Promise<T> {
		const client = new Client({ ...this.config, database: 'postgres' });

		await client.connect();

		try {
			return await action(client);
		} finally {
			await client.end();
		}
	}

	private async createScratchDatabase(name: string): Promise<void> {
		await this.onMaintenance(async (client) => {
			await client.query(`DROP DATABASE IF EXISTS "${name}"`);
			await client.query(`CREATE DATABASE "${name}"`);
		});
	}

	private async dropScratchDatabase(name: string): Promise<void> {
		await this.onMaintenance(async (client) => {
			await client.query(`DROP DATABASE IF EXISTS "${name}"`);
		});
	}

	private runTypeorm(
		args: string[],
		database: string,
	): Promise<{ stdout: string; stderr: string }> {
		return execFileAsync(
			'pnpm',
			[
				'exec',
				'tsx',
				'./node_modules/typeorm/cli.js',
				...args,
				'-d',
				dataSourcePath,
			],
			{
				cwd: basePath,
				env: { ...process.env, DB_NAME: database },
				maxBuffer: 32 * 1024 * 1024,
			},
		);
	}

	private async moveExistingMigrations(): Promise<number> {
		const files = (await readdir(migrationsPath)).filter((file) =>
			file.endsWith('.ts'),
		);

		if (files.length === 0) {
			return 0;
		}

		this.backupDir = path.join(backupPath, `${Date.now()}`);

		await mkdir(this.backupDir, { recursive: true });

		for (const file of files) {
			await rename(
				path.join(migrationsPath, file),
				path.join(this.backupDir, file),
			);
		}

		return files.length;
	}

	/**
	 * Clears the migrations directory before restoring, so a migration generated by the run
	 * that then failed does not survive alongside the originals it was meant to replace.
	 */
	private async restoreExistingMigrations(): Promise<void> {
		if (!this.backupDir || !existsSync(this.backupDir)) {
			return;
		}

		for (const file of await readdir(migrationsPath)) {
			if (file.endsWith('.ts')) {
				await rm(path.join(migrationsPath, file), { force: true });
			}
		}

		for (const file of await readdir(this.backupDir)) {
			await rename(
				path.join(this.backupDir, file),
				path.join(migrationsPath, file),
			);
		}

		await rm(this.backupDir, { recursive: true, force: true });
	}

	private async findGeneratedFile(): Promise<string> {
		const files = (await readdir(migrationsPath)).filter((file) =>
			file.endsWith('.ts'),
		);

		if (files.length !== 1) {
			throw new Error(
				`Expected exactly one generated migration, found ${files.length}`,
			);
		}

		return path.join(migrationsPath, files[0]);
	}

	/**
	 * Replays the consolidated migration against a throwaway database, then asks TypeORM
	 * whether any drift remains. "Up to date" is the only proof that the file actually
	 * reproduces the entities.
	 *
	 * The replay goes through `src/database/migrate.ts` rather than `migration:run`, because
	 * that is the entry point production uses and the only one that creates the non-public
	 * schemas first — TypeORM writes its `system.migrations` bookkeeping table before running
	 * anything, so the bare CLI fails on an empty database with `schema "system" does not
	 * exist`. Verifying through the CLI would test a path nobody deploys.
	 */
	private async verify(database: string): Promise<void> {
		await this.createScratchDatabase(database);

		try {
			await execFileAsync(
				'pnpm',
				['exec', 'tsx', './src/database/migrate.ts'],
				{
					cwd: basePath,
					env: { ...process.env, DB_NAME: database },
					maxBuffer: 32 * 1024 * 1024,
				},
			);

			const { stdout } = await this.runTypeorm(['schema:log'], database);

			if (!stdout.includes('Your schema is up to date')) {
				throw new Error(
					'Schema drift remains after running the consolidated migration',
				);
			}
		} finally {
			await this.dropScratchDatabase(database);
		}
	}

	/**
	 * Rewrites the migrations table of the working database so the consolidated migration
	 * counts as applied. The schema is already correct there; without this the next
	 * `migration:run` would try to create every table a second time.
	 */
	private async baseline(file: string): Promise<void> {
		const name = path.basename(file, '.ts');
		const [timestamp] = name.split('-');
		const className = `${name.slice(name.indexOf('-') + 1).replace(/(^|-)([a-z])/g, (_, __, letter) => letter.toUpperCase())}${timestamp}`;

		const client = new Client(this.config);

		await client.connect();

		try {
			await client.query('BEGIN');
			await client.query('DELETE FROM system.migrations');
			await client.query(
				'INSERT INTO system.migrations ("timestamp", "name") VALUES ($1, $2)',
				[Number(timestamp), className],
			);
			await client.query('COMMIT');
		} catch (error) {
			await client.query('ROLLBACK');
			throw error;
		} finally {
			await client.end();
		}
	}

	public async run(): Promise<void> {
		const suffix = Date.now();
		const generateDb = `${this.config.database}_consolidate_${suffix}`;
		const verifyDb = `${this.config.database}_verify_${suffix}`;

		display
			.blank()
			.text('Consolidating migrations', 'database')
			.indentMore()
			.bullet(`Working database: ${this.config.database}`)
			.bullet(`Scratch databases: ${generateDb}, ${verifyDb}`)
			.indentReset();

		if (!this.options.yes) {
			display
				.blank()
				.warning(
					'Every file in src/database/migrations will be replaced by a single migration',
				);

			if (!(await this.askConfirmation('Continue?'))) {
				display.blank().text('Process aborted', 'lock');

				return;
			}
		}

		let movedCount = 0;

		try {
			movedCount = await this.moveExistingMigrations();

			display
				.blank()
				.info(
					`Moved ${movedCount} migration(s) to ${this.backupDir || 'n/a'}`,
				);

			await this.createScratchDatabase(generateDb);

			try {
				await this.runTypeorm(
					[
						'migration:generate',
						`./src/database/migrations/${this.options.name}`,
					],
					generateDb,
				);
			} finally {
				await this.dropScratchDatabase(generateDb);
			}

			const file = await this.findGeneratedFile();

			display.success(`Generated ${path.basename(file)}`);

			await this.verify(verifyDb);

			display.success(
				'Verified on a fresh database — schema is up to date',
			);

			if (this.options.baseline) {
				await this.baseline(file);

				display.success(
					`Baselined ${this.config.database}: migrations table now lists only ${path.basename(file)}`,
				);
			}

			if (!this.options.keepBackup && this.backupDir) {
				await rm(this.backupDir, { recursive: true, force: true });

				display.info('Removed the migration backup');
			}

			display.blank().success('Consolidation complete');

			if (!this.options.baseline) {
				display
					.blank()
					.text(
						'Existing databases still list the old migrations.',
						'tip',
					)
					.indentMore()
					.bullet(
						'Re-run with --baseline to rewrite the migrations table',
					)
					.indentReset();
			}
		} catch (error) {
			display
				.blank()
				.error(error instanceof Error ? error.message : String(error));

			await this.restoreExistingMigrations();

			display.warning('Rolled back — original migrations restored');

			await this.dropScratchDatabase(generateDb);
			await this.dropScratchDatabase(verifyDb);

			process.exitCode = 1;
		} finally {
			this.rl.close();
		}
	}
}

const program = new Command();

program
	.name('migration-consolidate')
	.description(
		'Replace all migrations with a single one describing the current entity state',
	)
	.option('-n, --name <name>', 'Migration name', 'init')
	.option('-y, --yes', 'Skip the confirmation prompt', false)
	.option(
		'-b, --baseline',
		'Rewrite the working database migrations table to list only the new migration',
		false,
	)
	.option('--no-keep-backup', 'Delete the backup of the replaced migrations')
	.action(
		async (options: {
			name: string;
			yes: boolean;
			baseline: boolean;
			keepBackup: boolean;
		}) => {
			if (process.env.APP_ENV === 'production') {
				display.error('Refusing to run with APP_ENV=production');

				process.exit(1);
			}

			if (
				process.env.DB_CONNECTION &&
				process.env.DB_CONNECTION !== 'postgres'
			) {
				display.error(
					`Only the postgres connection is supported, got "${process.env.DB_CONNECTION}"`,
				);

				process.exit(1);
			}

			const consolidator = new MigrationConsolidator(
				{
					host: process.env.DB_HOST || 'localhost',
					port: Number.parseInt(process.env.DB_PORT || '5432', 10),
					user: process.env.DB_USER || 'root',
					password: process.env.DB_PASSWORD || '',
					database: process.env.DB_NAME || 'nready-app',
				},
				options,
			);

			await consolidator.run();
		},
	);

await program.parseAsync(process.argv);
